/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSheltersRouteImport } from './routes/app.shelters'
import { Route as AppMyDonationsRouteImport } from './routes/app.my-donations'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppDonateRouteImport } from './routes/app.donate'
import { Route as AppDistributionRouteImport } from './routes/app.distribution'
import { Route as AppDisastersRouteImport } from './routes/app.disasters'
import { Route as AppAreasRouteImport } from './routes/app.areas'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSheltersRoute = AppSheltersRouteImport.update({
  id: '/shelters',
  path: '/shelters',
  getParentRoute: () => AppRoute,
} as any)
const AppMyDonationsRoute = AppMyDonationsRouteImport.update({
  id: '/my-donations',
  path: '/my-donations',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppDonateRoute = AppDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributionRoute = AppDistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => AppRoute,
} as any)
const AppDisastersRoute = AppDisastersRouteImport.update({
  id: '/disasters',
  path: '/disasters',
  getParentRoute: () => AppRoute,
} as any)
const AppAreasRoute = AppAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/areas': typeof AppAreasRoute
  '/app/disasters': typeof AppDisastersRoute
  '/app/distribution': typeof AppDistributionRoute
  '/app/donate': typeof AppDonateRoute
  '/app/map': typeof AppMapRoute
  '/app/my-donations': typeof AppMyDonationsRoute
  '/app/shelters': typeof AppSheltersRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/areas': typeof AppAreasRoute
  '/app/disasters': typeof AppDisastersRoute
  '/app/distribution': typeof AppDistributionRoute
  '/app/donate': typeof AppDonateRoute
  '/app/map': typeof AppMapRoute
  '/app/my-donations': typeof AppMyDonationsRoute
  '/app/shelters': typeof AppSheltersRoute
  '/app': typeof AppIndexRoute
  '/app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/areas': typeof AppAreasRoute
  '/app/disasters': typeof AppDisastersRoute
  '/app/distribution': typeof AppDistributionRoute
  '/app/donate': typeof AppDonateRoute
  '/app/map': typeof AppMapRoute
  '/app/my-donations': typeof AppMyDonationsRoute
  '/app/shelters': typeof AppSheltersRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/areas'
    | '/app/disasters'
    | '/app/distribution'
    | '/app/donate'
    | '/app/map'
    | '/app/my-donations'
    | '/app/shelters'
    | '/app/'
    | '/app/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/areas'
    | '/app/disasters'
    | '/app/distribution'
    | '/app/donate'
    | '/app/map'
    | '/app/my-donations'
    | '/app/shelters'
    | '/app'
    | '/app/admin/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/areas'
    | '/app/disasters'
    | '/app/distribution'
    | '/app/donate'
    | '/app/map'
    | '/app/my-donations'
    | '/app/shelters'
    | '/app/'
    | '/app/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shelters': {
      id: '/app/shelters'
      path: '/shelters'
      fullPath: '/app/shelters'
      preLoaderRoute: typeof AppSheltersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-donations': {
      id: '/app/my-donations'
      path: '/my-donations'
      fullPath: '/app/my-donations'
      preLoaderRoute: typeof AppMyDonationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/donate': {
      id: '/app/donate'
      path: '/donate'
      fullPath: '/app/donate'
      preLoaderRoute: typeof AppDonateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distribution': {
      id: '/app/distribution'
      path: '/distribution'
      fullPath: '/app/distribution'
      preLoaderRoute: typeof AppDistributionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/disasters': {
      id: '/app/disasters'
      path: '/disasters'
      fullPath: '/app/disasters'
      preLoaderRoute: typeof AppDisastersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/areas': {
      id: '/app/areas'
      path: '/areas'
      fullPath: '/app/areas'
      preLoaderRoute: typeof AppAreasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAreasRoute: typeof AppAreasRoute
  AppDisastersRoute: typeof AppDisastersRoute
  AppDistributionRoute: typeof AppDistributionRoute
  AppDonateRoute: typeof AppDonateRoute
  AppMapRoute: typeof AppMapRoute
  AppMyDonationsRoute: typeof AppMyDonationsRoute
  AppSheltersRoute: typeof AppSheltersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAreasRoute: AppAreasRoute,
  AppDisastersRoute: AppDisastersRoute,
  AppDistributionRoute: AppDistributionRoute,
  AppDonateRoute: AppDonateRoute,
  AppMapRoute: AppMapRoute,
  AppMyDonationsRoute: AppMyDonationsRoute,
  AppSheltersRoute: AppSheltersRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
